GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFrdWIiLCJpYXQiOjE2NDMxNDEyNzUsImV4cCI6MTY0MzE0MTI5MH0.thEn-fA8-1f4Y3IryBqrKFJ6gYHL3saf-Uq6micT3R8

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFrdWIiLCJpYXQiOjE2NDMxNDEyNTN9.zjMewJ7wTzwnmeor0XbGzxGB8NzSSdZ1Cjns4vTkEEo"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFrdWIiLCJpYXQiOjE2NDMxNDEyNTN9.zjMewJ7wTzwnmeor0XbGzxGB8NzSSdZ1Cjns4vTkEEo"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Jakub"
}